public enum PosicionJugador {

    DELANTERO_CENTRAL,
    DELANTERO_IZQUIERDO,
    DELANTERO_DERECHO,
    CENTRAL,
    CENTRAL_IZQUIERDO,
    CENTRAL_DERECHO,
    DEFENSA_CENTRAL,
    DEFENSA_IZQUIERDA,
    DEFENSA_DERECHA,
    GUARDAMETA,
    APOYO_DELANTERO,
    APOYO_CENTRO,
    APOYO_DEFENSA,
    BANCA

}
